### ISSUE TITLE
Landmine (carrot bomb) trap mechanics

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Hunted#12]
Proximity based trap that explodes after 2-3s and kills nearby rabbits.

**Comment by GoogleFrog** [comment]
Kills, or throws violently into the air and then kills on impact?

**Comment by gajop** [comment]
current code just kills them, which is ok for now imo

**Comment by gajop** [comment]
https://github.com/SpringCabal/Hunted/commit/73b494a411431505250b42e6b82fd5dce7e324ce

**Comment by PicassoCT** [comment]
will make a landmine model after gun model.

**Comment by gajop** [comment]
works fine
