### ISSUE TITLE
Bunny Spawner

### ISSUE THREAD

**Issue by FLOZi** [SpringCabal/Hunted#14]
Made a framework for this already,

GG.FindBurrows() returns all exisiting burrows

GG.SpawnWaveWithAttributes(spawnSize, familySize, burrowFinder)
    -- spawnSize: number of rabbit families in this wave
    -- familySize: (maximum?) number of rabbits to emerge from a single burrow as a family
    -- burrowFinder: function to pass to restrict which burrows are used (TODO - purpose is to e.g. only allow burrows in the south of map, or only odd numbered etc)

atm for testing purposes each time you /give a burrow, the gadget will spawn up to 10 families each with up to 10 bunnies with the burrow for each family randomly selected from all existing burrows.

**Comment by FLOZi** [comment]
_feels guilty that he didn't reuse GFs tables of burrows and bunny defids_

**Comment by GoogleFrog** [comment]
That is ok. I am doubting that rabbit AI will pay attention to burrow at all. Even if they did burrows would be treated a lot like carrots. What do you need bunny defs for? I thought you were just spawning them.

**Comment by GoogleFrog** [comment]
Bunnys are being spawned.
