### ISSUE TITLE
grid extensions

### ISSUE THREAD

**Issue by gajop** [SpringCabal/Hunted#16]
Grid extensions would make it look better imo

**Comment by GoogleFrog** [comment]
Map edge extension?

**Comment by gajop** [comment]
yeah

**Comment by GoogleFrog** [comment]
Fixed https://github.com/SpringCabal/Hunted/commit/54d672a10f7f7c35e51f693ab242063ef3d49ea5

Not so sure that it is required. Who knows whether the camera will be fixed.
