### ISSUE TITLE
Camera controls

### ISSUE THREAD

**Issue by GoogleFrog** [SpringCabal/Hunted#17]
Consider the camera controls. Also a fixed camera may work.
![screen00219](https://cloud.githubusercontent.com/assets/1318249/9153983/fe22f366-3ebe-11e5-8aa3-09e7d9fab32f.png)

**Comment by GoogleFrog** [comment]
![screen00220](https://cloud.githubusercontent.com/assets/1318249/9154039/b6aa2b46-3ec1-11e5-8937-fddb1d8a6f6d.png)

**Comment by gajop** [comment]
https://github.com/SpringCabal/Hunted/commit/1f41c4e397772fe3d9b60890c19096dadaac6af2

**Comment by gajop** [comment]
works fine atm, maybe tweak later
