### ISSUE TITLE
Create PlaceHolder

### ISSUE THREAD

**Issue by PicassoCT** [SpringCabal/Hunted#2]
Create a PlaceHolderModel for 
- [x] Hole
- [x] Bunny
- [x] Shotgun
- [x] Carrot

**Comment by gajop** [comment]
we probably don't need a model for the shotgun, just the effect/sound when shooting

**Comment by ashdnazg** [comment]
add Carrot

**Comment by PicassoCT** [comment]
@gajop  How do we transport the kickback and reloading without a modell?

**Comment by gajop** [comment]
this is all done
