### ISSUE TITLE
Springsettings are bad

### ISSUE THREAD

**Issue by GoogleFrog** [SpringCabal/Hunted#23]
The springsettings for the build are bad. They show a window (not a borderless window) so scrolling is messed up. Also zoom is inverted and map scrolling is unintuitive.

In the future there should be a repo which represents the final release. It would contain exactly what the install will look like. Failing that it should contain the settings for an install.

Here are some good settings. Perhaps it is enough to use them each time. http://pastebin.com/J716ie72

**Comment by gajop** [comment]
fixed in the newest release. repos and scripts on the TODO
