### ISSUE TITLE
Minimum required Gadgets

### ISSUE THREAD

**Issue by ashdnazg** [SpringCabal/Hunted#3]
Gadgets:
- [x] Rabbits AI - move towards carrots, move from/to burrows, run from shotgun, remove eaten carrots. (takes care of individual units) - rabbit_ai.lua
- [x] Waves - Rabbit spawner - wave_spawner.lua
- [x] Carrot counting and game over - game_end.lua
- [x] Shotgun projectile spawner - shotgun.lua
- [x] Trap placement (can use a similar interface to scened?) - traps.lua

**Comment by FLOZi** [comment]
MCL arty strike might be modified for shotgun, though the light might be built in to it too?

**Comment by ashdnazg** [comment]
I want the light to be in widget land

**Comment by GoogleFrog** [comment]
I will have a go at rabbit AI

**Comment by GoogleFrog** [comment]
I have added a placeholder for shotgun.

**Comment by GoogleFrog** [comment]
Completed carrot counting and game over.

**Comment by GoogleFrog** [comment]
Mine can be placed with left mouse button. We decided not to have a trap placement phase so there is nothing else to be done.
