### ISSUE TITLE
What is going on

### ISSUE THREAD

**Issue by GoogleFrog** [SpringCabal/Hunted#6]

**Comment by ScarylePoo** [comment]
https://docs.google.com/document/d/1VAr0n2K7U7rkf-OLLGSs7YrK8fmq_XYribdLp80VOdw/edit#heading=h.4dd68mbyswcm

**Comment by GoogleFrog** [comment]
What are the communication channels. Just Mumble? I head something about google hangouts.

**Comment by ScarylePoo** [comment]
We were trying to use hangouts, but flozi didn't have his set up to allow hangouts and so we just said screwit for the most part. Chat should happen in hangouts though, so that we have history. I'll invite you to the group chat.

Edit: You are already invited to the hangout.

**Comment by GoogleFrog** [comment]
Ok, got it.
