### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by ScarylePoo** [SpringCabal/Hunted#7]
- [ ] eating a carrot
- [x] ambient map sounds (crickets)
- [ ] Hopping Sounds
- [ ] Coming out of hole
- [ ] Escaping into hole
- [x] Splat Explosions
- [ ] Burn sounds / sizzle?
- [ ] Explosions?
- [x] Shotgun Sound
- [ ] Rabbits “Shagging”
- [x] Flashlight on/off

**Comment by ScarylePoo** [comment]
For the record: I'm not at all happy with the splat sounds.

**Comment by gajop** [comment]
this is outdated, i think we have all sounds needed, for missing ones open a new issue
