### ISSUE TITLE
Write initial rabbit AI

### ISSUE THREAD

**Issue by GoogleFrog** [SpringCabal/Hunted#9]

**Comment by ashdnazg** [comment]
[f=0000970] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/rabbit_ai.lua"]:437: attempt to index field '?' (a nil value)
stack traceback:
    [string "LuaRules/Gadgets/rabbit_ai.lua"]:437: in function 'UpdateRabbit'
    [string "LuaRules/Gadgets/rabbit_ai.lua"]:520: in function 'GameFrame'
    [string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
    (tail call): ?

after last commit, I think it's from multiple bunnies eating same carrot?

**Comment by GoogleFrog** [comment]
Fixed. https://github.com/SpringCabal/Hunted/commit/a11bb6b69b80f88aa2be2ad1787ff92b1098718b

**Comment by GoogleFrog** [comment]
So this is mostly done (for the initial section). The the rabbit gadget supports:
- Areas of sudden fear (GG.ScareRabbitsInArea). Use this on the impact of weapons etc... to make them scatter.
- Areas of constant fear, no interface yet. But use this instead of repeating sudden fear from elsewhere. Perhaps put low constant fear on the fields (it is open), on scary looking sprung traps (eg run away from a stuck rabbit) or for some time after a weapon impact.
- Goal areas. Similar to areas of fear. Currently Carrots and Burrows are goals.
- Carrot eating. Rabbits will eat a carrot if they run into it. They are likely to run into carrots because they are set as goals. Too much fear will interrupt eating.

Burrow entering is not in as it seems like a pointless feature. It could be added though, simply set the burrow as a goal and do some handling if a collision occurs.

**Comment by gajop** [comment]
The rabbits tend to end up in the top-left area of the map, I guess movement isn't uniformly random

**Comment by GoogleFrog** [comment]
It should not be, which map?

**Comment by gajop** [comment]
https://github.com/SpringCabal/Hunted-Map

**Comment by GoogleFrog** [comment]
If a unit is told to move towards a 3rd order compass point (for example North North East or East South East) how does its movement interact with the 8 point directions of Spring? Does the unit preference North West movement first? That could cause the bias.

**Comment by GoogleFrog** [comment]
I strongly suspect that 8-point movement bias was the cause of the bug. This is because I fixed the bug by using raw move goals. These move goals do not trigger pathfinder so do not get an 8-direction bias.  Note however that rabbits no longer do any pathfinding (this should not be a problem).

**Comment by FLOZi** [comment]
Currently bunny AI makes them try and get straight back into the burrows rather than seeking carrots. -> Bunny goals need to be dynamic

**Comment by GoogleFrog** [comment]
I had not considered burrows at that point. Rabbits now move towards Carrots, dig them out of the ground then pick them up and take them back to their burrow. Once a carrot has been dropped off they return for more.

I consider the rabbit AI mostly complete at this point. It may need extension later but is done for now. New comments or bug reports should go to their own tickets.
